{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: momo-frontend
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: momo-store
    env: "{{ .Values.environment }}"
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.rewriteTarget }}
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and .Values.ingress.tls.enabled .Values.fqdn }}
  tls:
    - hosts:
        - {{ .Values.fqdn | quote }}
      secretName: {{ .Release.Name }}-frontend-tls
  {{- end }}
  rules:
    - {{- if .Values.fqdn }}
      host: {{ .Values.fqdn | quote }}
      http:
    {{- else }}
      http:
    {{- end }}
        paths:
          - path: {{ .Values.ingress.path | default "/momo-store(/|$)(.*)" | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ .Values.service.port }}
{{- end }}
