---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: ${VAULT_TOKEN_BASE64}
  mongodb_uri: ${SPRING_DATA_MONGODB_URI_BASE64}
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_CONFIG_JSON_BASE64}
