---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: app-backend
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: app
    env: "production"
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: app-backend
    app.kubernetes.io/instance: app 