---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: momo-frontend
    app.kubernetes.io/instance: momo-store
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: momo-store
    env: "production"
spec:
  replicas: 1
  revisionHistoryLimit: 12
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: momo-frontend
      app.kubernetes.io/instance: momo-store
  template:
    metadata:
      labels:
        app.kubernetes.io/name: momo-frontend
        app.kubernetes.io/instance: momo-store
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: momo-store
        env: "production"
    spec:
      containers:
        - name: frontend
          image: gitlab.praktikum-services.ru:5050/std-ext-021-21/momo-store/momo-frontend:latest
          imagePullPolicy: IfNotPresent
          command: ["/usr/sbin/nginx"]
          args: ["-g", "daemon off;"]
          ports:
            - name: frontend
              containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 6
      volumes:
        - name: nginx-config
          configMap:
            name: frontend
      imagePullSecrets:
        - name: docker-config-secret

