# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_CONFIG_JSON_BASE64}
