---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: momo-frontend
    app.kubernetes.io/instance: momo-store
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: momo-store
    env: "production"
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: momo-frontend
    app.kubernetes.io/instance: momo-store
